## 2.3 Overall Flow

![](img/2.3-Tensorflow-blackbox-01.jpg)

In **Tensorflow**, everything is executed within the context of session. Either you can pass it explicitely or pass it implicitely by using

>```python  
>with tf.Session() as sess : 
>    #evaluate the variables of computational graph
>    #update the tensors 
>    pass
>``` 

Within the scope, you can obtain the resultant tensor by evaluating the operation-based dependency Tree.   
## 2.4 Placeholder
If you want to assign the value of tensor in run-time, then using **tf.placeholder** is wise choice. tf.placeholder allows the user to enter changing values in a loop reciding inside the session. For example, if you want to pass a batch of images on fly, it makes sense, to have the tensor corrosponding to image as *tf.placeholder* instead of *tf.constant*.  

In the example bellow, we will be looking at creation of fibonacci series via placeholders
#### 2.4.1 Creating a fibonacci series

In [5]:
#Creating a Fibonacci Series Example 1
import tensorflow as tf;
_a,_b = 0,1
a = tf.placeholder(dtype=tf.int64)
b = tf.placeholder(dtype=tf.int64)

with tf.Session() as sess:
    for i in range(10):
        print (_a,end=" ")
        _a,_b = sess.run([b,a+b],feed_dict={a:_a,b:_b})


0 1 1 2 3 5 8 13 21 34 

In [3]:
#Creating a Fibonacci Series Example 2
import tensorflow as tf;
a = tf.placeholder(dtype=tf.int64)
b = tf.placeholder(dtype=tf.int64)
lst = [0,1]

with tf.Session() as sess:
    for i in range(10):
        lst.append(sess.run(a+b,feed_dict={a:lst[-2],b:lst[-1]}))
print (lst)


[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


#### 2.4.2 Matrix Vector Multiplication in tensorflow

In [13]:
import tensorflow as tf
import numpy as np
matrix = tf.placeholder(dtype=tf.float32,shape=(3,4))
vector = tf.placeholder(dtype=tf.float32,shape=(4,1))
output = tf.matmul(matrix,vector);

with tf.Session() as sess:
    matrix_val = np.arange(12).reshape(3,4)
    vector_val = np.arange(4).reshape(4,1)
    output_val = output.eval(feed_dict={matrix: matrix_val, vector: vector_val})
    print ('matrix_val is \n%s\n'%matrix_val)
    print ('vector_val is \n%s\n'%vector_val)
    print ('output_val is \n%s\n'%output_val )

matrix_val is 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

vector_val is 
[[0]
 [1]
 [2]
 [3]]

output_val is 
[[14.]
 [38.]
 [62.]]



#### 2.4.3 Evaluate :  $\left. \cfrac{d}{dx}(2x^2) \right\vert_{(x=3)} $
I have attached a simple example of doing differentiation and finding gradient of a function in Tensorflow


In [ ]:
# Finding the derivative of function 
import tensorflow as tf;
x= tf.placeholder(tf.float32);
fx =2*x*x;
grads =tf.gradients(fx,x)
with tf.Session() as sess:
    print (sess.run(grads,feed_dict={x:3.0}))


#### 2.4.3 Evaluate :  $\left. \nabla (2x^2 + 3y^2) \right\vert_{(x=3,y=5)} $
I have attached a simple example of doing differentiation and finding gradient of a function in Tensorflow


In [15]:
# Finding the gradient of function 
x= tf.placeholder(tf.float32);
y= tf.placeholder(tf.float32);
fxy =2*x*x+3*y*y;
grads =tf.gradients(fxy,[x,y])
with tf.Session() as sess:
    print (sess.run(grads,feed_dict={x:3.0,y:5.0}))

[12.0, 30.0]
