## 2.5 Variables in Tensorflow
A variable maintains the state in the graph itself. In tensorflow graph, the nodes are the operations and the edges are data. But the **exception** to the rule is tf.Variable. It is an **operation/node in the Graph, which maintains data/state**.   
Thats why, use of *tf.Variable is essential for stateful models*. It also comes with assign function.

> **Note :** *tf.Variable is a function which takes tensors and initializers as input to construct a variable in Graph*  

![](img/2.5.1-variable-graph.jpg)

In [1]:
import tensorflow as tf;

In [2]:
log_path='model/2.5.1-exp'
graph = tf.Graph()
with graph.as_default():
    a = tf.Variable(3)

In [3]:
for i,op in enumerate(graph.get_operations()):
    print ('----------------------- \nOperation %i is \n%s\n'%(i,op))

----------------------- 
Operation 0 is 
name: "Variable/initial_value"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_INT32
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_INT32
      tensor_shape {
      }
      int_val: 3
    }
  }
}


----------------------- 
Operation 1 is 
name: "Variable"
op: "VariableV2"
attr {
  key: "container"
  value {
    s: ""
  }
}
attr {
  key: "dtype"
  value {
    type: DT_INT32
  }
}
attr {
  key: "shape"
  value {
    shape {
    }
  }
}
attr {
  key: "shared_name"
  value {
    s: ""
  }
}


----------------------- 
Operation 2 is 
name: "Variable/Assign"
op: "Assign"
input: "Variable"
input: "Variable/initial_value"
attr {
  key: "T"
  value {
    type: DT_INT32
  }
}
attr {
  key: "_class"
  value {
    list {
      s: "loc:@Variable"
    }
  }
}
attr {
  key: "use_locking"
  value {
    b: true
  }
}
attr {
  key: "validate_shape"
  value {
    b: true
  }
}


----------------------- 
Operation 3 is 
name: "Variable/

In [8]:
# Writing in Tensorboard
#tf.summary.FileWriter(logdir='model/2.5.1-exp',graph=graph)

Let us look into some of the examples of usage of variables
#### 2.5.1 Assigning constant to tf.Variable and incrementing it


In [20]:
a = tf.constant(3)
b = tf.Variable(a+3)

with tf.Session() as sess:
    b.initializer.run() # Use sess.run or Operation.run for running initializer
    print (b.eval())

6


#### 2.5.2 Using zeros initializer and tf.get_variable  
**tf.get_variable(name, shape, initializer)**  

tf.get_variable is recommended function for creating a tensorflow variable(avoid use of tf.Variable). This takes care of corner cases like 
* name is a required argument, which helps the user to identify and vizualize a variabe in  tensorboard.
* tf.get_variable doesn't create variable if it already exists with the same name (a common issue in jupyter notebooks)

In [1]:
import tensorflow as tf;
var = tf.get_variable(name='var',shape=(3,5),initializer=tf.zeros_initializer())
with tf.Session() as sess:
    var.initializer.run()
    print (var.eval())

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 2.5.3 Using Global Initializer
*tf.global_variables_initializer()* returns an *operation* which initializes all the variables present in the graph. This helps, because now, we don't need to initialize individual variables *seperately* anymore

In [3]:
import tensorflow as tf;
x = tf.get_variable(name='x',shape=(),initializer=tf.zeros_initializer())
y = tf.get_variable(name='y',shape=(),initializer=tf.ones_initializer())
z = x + y
initializer = tf.global_variables_initializer()
with tf.Session() as sess:
    initializer.run()
    print(z.eval())
    

1.0
